#!/usr/bin/env ruby
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# Created 2/21/2013

def brute_force(num)
  cur_num = 1
  prev_num = 1
  temp = 0
  total = 0
  while cur_num < num
   if cur_num % 2 == 0
     total += cur_num
   end
   temp = cur_num
   cur_num = cur_num + prev_num
   prev_num = temp
  end
   puts "Prev num = #{prev_num}, cur num = #{cur_num}, total is #{total}"
end

brute_force(4000000)

